<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MEGCP4U" name="HoldActiveCancel_US_main.CreateRequest_Cancel" tests="3" failures="1" timestamp="7 Sep 2021 02:54:02 GMT" time="30.321" errors="0">
  <testcase name="RIPC_Login" time="20.909" classname="HoldActiveCancel_US_main.CreateRequest_Cancel"/>
  <testcase name="reqstatus" time="2.764" classname="HoldActiveCancel_US_main.CreateRequest_Cancel">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;[On hol]d&gt; but was:&lt;[Cancele]d&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[On hol]d> but was:<[Cancele]d>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at HoldActiveCancel_US.Step05_CreateRequest_Cancel.reqStatus(Step05_CreateRequest_Cancel.java:209)
	at HoldActiveCancel_US_main.CreateRequest_Cancel.reqstatus(CreateRequest_Cancel.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- reqstatus -->
  <testcase name="holdAction" time="6.648" classname="HoldActiveCancel_US_main.CreateRequest_Cancel"/>
</testsuite> <!-- HoldActiveCancel_US_main.CreateRequest_Cancel -->
